version: "3.8"
services:
  nfs:
    image: easypi/nfs
    ports:
      - "2049:2049"
    volumes:
      - ./data:/data
    environment:
      - EXPORT_ID=0
      - EXPORT_PATH=/data
      - PSEUDO_PATH=/
    privileged: true
    restart: unless-stopped
